# Generated by Django 4.1.2 on 2023-01-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.CharField(default='NEW10', max_length=100),
        ),
    ]
