# Generated by Django 4.1.2 on 2023-01-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discount',
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.CharField(default='NEW10', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='discounted_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
