# Generated by Django 4.1.2 on 2023-01-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_user_discount_cart_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='made_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.user'),
            preserve_default=False,
        ),
    ]
